### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by JordanMartinez** [garyb/purescript-codec#4]
Although [codec](https://hackage.haskell.org/package/codec-0.2.1) is a library that exists in Haskell and was the library on which this one is based, it seems like it's author has stopped working on the library.

I'd like to port this library to Haskell. Then, I can create a server that uses that ported library to serialize things and hopefully play with with this library on the PS side of things.

However, you don't have a license, so I feel like doing anything like that wouldn't end well until it's clarified.

**Comment by garyb** [comment]
It's MIT licenced as per the `bower.json`, but I'll add the licence file proper 🙂

**Comment by JordanMartinez** [comment]
Ah, thanks!
